### ISSUE TITLE
GamecubeConsole::Detect does not detect normal polls

### ISSUE THREAD

**Issue by CarVac** [JonnyHaystack/joybus-pio#4]
This affects BootMii which only sends the poll command, not probe

**Comment by CarVac** [comment]
I just tried this and it still doesn't work in bootmii... will try to investigate after the weekend

**Comment by JonnyHaystack** [comment]
Hmm, that's odd. It was definitely working for me. Do you know which version of BootMii you're on? I can try to find out which version I have as well. My homebrew setup is from 2015.

I would've taken a look at the signalling myself, but it's not super easy for me to relocate my Wii setup near to my PC to use my logic analyzer with it.
